apps:
  - name: argocd-apps
    namespace: argocd
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-argocd-apps.git
      path: charts/argocd-apps

# User-facing apps
  - name: libreddit
    namespace: prd
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-apps.git 
      path: charts/libreddit
  - name: audiobookshelf
    namespace: prd
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-apps.git 
      path: charts/audiobookshelf
  - name: komga
    namespace: prd
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-apps.git 
      path: charts/komga
  - name: plex
    namespace: prd
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-apps.git 
      path: charts/plex
  - name: mangathr
    namespace: mangathr
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-apps.git 
      path: charts/mangathr
  - name: excalidraw
    namespace: prd
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-apps.git
      path: charts/excalidraw
  - name: rimgo
    namespace: prd
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-apps.git
      path: charts/rimgo
  - name: your-spotify
    namespace: prd
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-apps.git
      path: charts/your-spotify

  - name: tfc-agent
    namespace: prd
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-apps.git
      path: charts/tfc-agent

# Cluster apps
  - name: datadog
    namespace: kube-system
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-cluster.git 
      path: charts/datadog
  - name: k8s-dashboard
    namespace: kubernetes-dashboard
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-cluster.git 
      path: charts/k8s-dashboard
  - name: metallb-sys
    namespace: metallb-system
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-cluster.git 
      path: charts/metallb-sys
  - name: metallb-conf
    namespace: metallb-system
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-cluster.git 
      path: charts/metallb-conf
  - name: cert-manager
    namespace: cert-manager
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-cluster.git 
      path: charts/cert-manager
  - name: rancher-local-path
    namespace: default # doesn't matter, since resources are not namespaced
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-cluster.git 
      path: charts/rancher-local-path
  - name: ingress-nginx
    namespace: ingress
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-cluster.git 
      path: charts/ingress-nginx
  - name: csi-driver-nfs
    namespace: kube-system
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-cluster.git 
      path: charts/csi-driver-nfs

  - name: vault
    namespace: vault
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-vault.git
      path: .
