apps:
  - name: argocd-apps
    namespace: argocd
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-argocd-apps.git
      path: charts/argocd-apps

# User-facing apps
  - name: libreddit
    namespace: prd
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-apps.git 
      path: charts/libreddit
  - name: audiobookshelf
    namespace: prd
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-apps.git 
      path: charts/audiobookshelf
  - name: komga
    namespace: prd
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-apps.git 
      path: charts/komga
  - name: plex
    namespace: prd
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-apps.git 
      path: charts/plex
  - name: mangathr
    namespace: mangathr
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-apps.git 
      path: charts/mangathr
  - name: excalidraw
    namespace: prd
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-apps.git
      path: charts/excalidraw
  - name: rimgo
    namespace: prd
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-apps.git
      path: charts/rimgo

# Cluster apps
  - name: datadog
    namespace: kube-system
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-cluster.git 
      path: charts/datadog
  - name: k8s-dashboard
    namespace: kubernetes-dashboard
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-cluster.git 
      path: charts/k8s-dashboard
  - name: metallb-sys
    namespace: metallb-system
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-cluster.git 
      path: charts/metallb-sys
  - name: metallb-conf
    namespace: metallb-system
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-cluster.git 
      path: charts/metallb-conf
  - name: cert-manager
    namespace: cert-manager
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-cluster.git 
      path: charts/cert-manager
