apps:
  - name: argocd-apps
    namespace: argocd
    valueFiles:
      - values_sol-k8s.yaml
    repo:
      url: https://github.com/browningluke-iac/helm-argocd-apps.git
      path: charts/argocd-apps
